
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2015     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/


//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the timing class for NetworkSwitchLevel1.
//*
//* This is a template file: You may modify this file to implement the 
//* timing behavior of your component.
//* The functions below allows advance users to customize the timing behavior of your model.
//* 
//* Model Builder version: 4.2.1
//* Generated on: Aug. 15, 2016 12:15:23 PM, (user: kenm)
//*>


#include "NetworkSwitchLevel1_t.h"


#include <iostream>

using namespace std;
using namespace sc_dt;
using namespace sc_core;

NetworkSwitchLevel1_t_base* NetworkSwitchLevel1_t_base::create_t(const char* name, long simulation) {
  return new NetworkSwitchLevel1_t(name, simulation);
}

NetworkSwitchLevel1_t::NetworkSwitchLevel1_t(sc_module_name _name, long simulation)
  : NetworkSwitchLevel1_t_base(_name, simulation) {
  
}

