
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2015     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the PV class for SensorNodeLevel1.
//* This is a template file: You may modify this file to implement the 
//* behavior of your component. 
//* 
//* Model Builder version: 4.2.1
//* Generated on: Aug. 15, 2016 12:15:59 PM, (user: kenm)
//*>


#pragma once

#include "SensorNodeLevel1_model.h"

using namespace tlm;

//This class inherits from the SensorNodeLevel1_pv_base class
class SensorNodeLevel1_pv : public SensorNodeLevel1_pv_base {
 public:
  typedef esl::tlm_types::Address mb_address_type;
 public:
  // Constructor
  // Do not add parameters here.
  // To add parameters - use the Model Builder form (under PV->Parameters tab)
  SC_HAS_PROCESS(SensorNodeLevel1_pv);
  SensorNodeLevel1_pv(sc_core::sc_module_name module_name);    

 protected:
  ////////////////////////////////////////
  // target ports read callbacks
  //////////////////////////////////////// 
  bool NetworkSlave_callback_read(mb_address_type address, unsigned char* data, unsigned size);
  
  unsigned NetworkSlave_callback_read_dbg(mb_address_type address, unsigned char* data, unsigned size); 

 protected:
  ////////////////////////////////////////
  // target ports write callbacks
  //////////////////////////////////////// 
  bool NetworkSlave_callback_write(mb_address_type address, unsigned char* data, unsigned size);
  
  unsigned NetworkSlave_callback_write_dbg(mb_address_type address, unsigned char* data, unsigned size);  
  bool NetworkSlave_get_direct_memory_ptr(mb_address_type address, tlm::tlm_dmi& dmiData);

  ////////////////////////////////////////
  // User Code
  //////////////////////////////////////// 
  void IntervalSampleThread();
  sc_event IntervalSampleEvent;

  void MainThread();
  sc_event AcknowledgeEvent;
  bool AcknowledgeMessageReceived;
};

