
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2015     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the PV class for SystemControllerLevel1.
//* This is a template file: You may modify this file to implement the 
//* behavior of your component. 
//* 
//* Model Builder version: 4.2.1
//* Generated on: Aug. 15, 2016 12:30:04 PM, (user: kenm)
//*>


#pragma once

#include "SystemControllerLevel1_model.h"

using namespace tlm;

//This class inherits from the SystemControllerLevel1_pv_base class
class SystemControllerLevel1_pv : public SystemControllerLevel1_pv_base {
 public:
  typedef esl::tlm_types::Address mb_address_type;
 public:
  // Constructor
  // Do not add parameters here.
  // To add parameters - use the Model Builder form (under PV->Parameters tab)
  SC_HAS_PROCESS(SystemControllerLevel1_pv);
  SystemControllerLevel1_pv(sc_core::sc_module_name module_name);    

 protected:
  ////////////////////////////////////////
  // target ports read callbacks
  //////////////////////////////////////// 
  bool Slave_callback_read(mb_address_type address, unsigned char* data, unsigned size);
  
  unsigned Slave_callback_read_dbg(mb_address_type address, unsigned char* data, unsigned size); 

 protected:
  ////////////////////////////////////////
  // target ports write callbacks
  //////////////////////////////////////// 
  bool Slave_callback_write(mb_address_type address, unsigned char* data, unsigned size);
  
  unsigned Slave_callback_write_dbg(mb_address_type address, unsigned char* data, unsigned size);  
  bool Slave_get_direct_memory_ptr(mb_address_type address, tlm::tlm_dmi& dmiData);   

  ////////////////////////////////////////
  // User Code
  //////////////////////////////////////// 
  void ProcessThread();
  unsigned short max_sample;
  unsigned int min_sample;
  unsigned int PortWidthFactor;
  sc_time PortClock;
};

