
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2015     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the PV class for WaveSampleGenerator.
//* This is a template file: You may modify this file to implement the 
//* behavior of your component. 
//* 
//* Model Builder version: 4.2.1
//* Generated on: Aug. 12, 2016 06:35:19 AM, (user: kenm)
//* Automatically merged on: Aug. 12, 2016 09:06:39 AM, (user: kenm)
//* Automatically merged on: Aug. 12, 2016 09:08:12 AM, (user: kenm)
//*>



#include "WaveSampleGenerator_pv.h"
#include <iostream>

using namespace sc_core;
using namespace sc_dt;
using namespace std;

//constructor
WaveSampleGenerator_pv::WaveSampleGenerator_pv(sc_module_name module_name) 
  : WaveSampleGenerator_pv_base(module_name) {
}      

// Read callback for Slave port.
// Returns true when successful.
bool WaveSampleGenerator_pv::Slave_callback_read(mb_address_type address, unsigned char* data, unsigned size) {
  if (size == 2) {
    unsigned short * value = data;
    double period = Period.to_double();
    double current_time = sc_time_stamp().to_double();
    double ratio = current_time / period;
    double integer = M_PI;
    double fractional = modf(ratio, & integer);
    double signal = (sin(fractional * M_PI) * (Max -Min)) + Min;
    *value = (unsigned short)signal;
    return true;
  }
  return true;
}

// Write callback for Slave port.
// Returns true when successful.
bool WaveSampleGenerator_pv::Slave_callback_write(mb_address_type address, unsigned char* data, unsigned size) {
  
  return true;
} 




unsigned WaveSampleGenerator_pv::Slave_callback_read_dbg(mb_address_type address, unsigned char* data, unsigned size) {
  return 0;
} 

unsigned WaveSampleGenerator_pv::Slave_callback_write_dbg(mb_address_type address, unsigned char* data, unsigned size) {
  return 0;
} 

bool WaveSampleGenerator_pv::Slave_get_direct_memory_ptr(mb_address_type address, tlm::tlm_dmi& dmiData) {
  return false;
}

 

// in order to minimize merging conflicts, we recommend to add your functions after this comment
